FROM python:3.10
WORKDIR /app

# 安装依赖
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# 复制源代码（放在依赖之后，便于 Docker 缓存）
COPY . .

# 暴露端口
EXPOSE 9099

# 启动命令
CMD ["python", "app.py", "--env=dockermy"]
